language: node_js
node_js:
  - "4.2.1"
jdk:
  - oraclejdk8
install:
  - set -ev
  - npm install -g bower
  - npm install -g grunt-cli
  - ./gradlew assemble
script:
  - ./gradlew check
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - ./gradlew bootRun &
  - bootPid=$!
  - sleep 30s
  - grunt itest
